/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import org.junit.Test;

public class AppTest {
	@Test
	public void appHasAGreeting() {
		App classUnderTest = new App();
		assertNotNull("app should have a greeting", classUnderTest.getGreeting());
	}

	@Test
	public void testAppReternHelloWorld() {
		App classUnderTest = new App();
		assertEquals("Hello World!", classUnderTest.getGreeting());
	}
}
